"""
端口层模块

定义六边形架构的核心接口。
"""

from __future__ import annotations

from ..context import (
    KernelContext,
    KernelResult,
    ExecutionTrace,
    IterationTrace,
    ToolCallTrace,
    PlanPort,
    Plan,
    PlanStep,
    StepStatus,
    PlanEvaluation,
    SkillPort,
    Skill,
    SkillResult,
    SkillInstallResult,
    EvalPort,
    TestCase,
    TestSuite,
    EvalResult,
    BenchmarkResult,
)

from .memory import (
    MemoryPort,
    MemoryAdapter,
    MemoryRegistry,
    Memory,
    MemoryType,
    MemoryPriority,
    MemoryQuery,
    MemoryResult,
    MemoryStats,
    StoreContext,
    RetrieveContext,
    GetContext,
    UpdateContext,
    DeleteContext,
    ConsolidationContext,
    ConsolidationResult,
    MemoryAdapterConfig,
)

from .tools import (
    ToolPort,
    ToolAdapter,
    ToolRegistry,
    ToolHandler,
    Tool,
    ToolCategory,
    ToolPermission,
    ToolCall,
    ToolResult,
    ToolValidationResult,
    ToolContext,
    ToolHandlerFactory,
    ToolAdapterConfig,
)

from .model import (
    ModelPort,
    ModelAdapter,
    ModelRegistry,
    ModelRouter,
    RoutingRule,
    Message,
    MessageRole,
    ToolDefinition,
    ToolCall as ModelToolCall,
    ToolCallResult,
    ModelResponse,
    ModelUsage,
    EmbeddingResponse,
    ModelConfig,
    ModelProvider,
    BatchChatRequest,
    StreamChunk,
)

from .skills import (
    SkillPort as SkillSystemPort,
    SkillCategory,
)

from .collaboration import (
    CollaborationPort,
    CollaborationRegistry,
    AgentMailbox,
    InProcessCollaborationAdapter,
    AgentMessage,
    MessageType,
    TaskRequest,
    TaskResult,
    AgentHealth,
    AgentRole,
    CollaborationContext,
)

__all__ = [
    # 上下文
    "KernelContext",
    "KernelResult",
    "ExecutionTrace",
    "IterationTrace",
    "ToolCallTrace",
    "PlanPort",
    "Plan",
    "PlanStep",
    "StepStatus",
    "PlanEvaluation",
    # 记忆端口
    "MemoryPort",
    "MemoryAdapter",
    "MemoryRegistry",
    "Memory",
    "MemoryType",
    "MemoryPriority",
    "MemoryQuery",
    "MemoryResult",
    "MemoryStats",
    "StoreContext",
    "RetrieveContext",
    "GetContext",
    "UpdateContext",
    "DeleteContext",
    "ConsolidationContext",
    "ConsolidationResult",
    "MemoryAdapterConfig",
    # 工具端口
    "ToolPort",
    "ToolAdapter",
    "ToolRegistry",
    "ToolHandler",
    "Tool",
    "ToolCategory",
    "ToolPermission",
    "ToolCall",
    "ToolResult",
    "ToolValidationResult",
    "ToolContext",
    "ToolHandlerFactory",
    "ToolAdapterConfig",
    # 模型端口
    "ModelPort",
    "ModelAdapter",
    "ModelRegistry",
    "ModelRouter",
    "RoutingRule",
    "Message",
    "MessageRole",
    "ToolDefinition",
    "ModelToolCall",
    "ToolCallResult",
    "ModelResponse",
    "ModelUsage",
    "EmbeddingResponse",
    "ModelConfig",
    "ModelProvider",
    "BatchChatRequest",
    "StreamChunk",
    # 技能端口
    "SkillPort",
    "SkillSystemPort",
    "Skill",
    "SkillCategory",
    "SkillResult",
    "SkillInstallResult",
    # 评测端口
    "EvalPort",
    "TestCase",
    "TestSuite",
    "EvalResult",
    "BenchmarkResult",
    # 协作端口
    "CollaborationPort",
    "CollaborationRegistry",
    "AgentMailbox",
    "InProcessCollaborationAdapter",
    "AgentMessage",
    "MessageType",
    "TaskRequest",
    "TaskResult",
    "AgentHealth",
    "AgentRole",
    "CollaborationContext",
]
